test1<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test2<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test3<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test4<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test5<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test6<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test7<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test8<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test9<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test10<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test11<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test12<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test13<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test14<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test15<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test16<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test17<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test18<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test19<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test20<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test21<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test22<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test23<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test24<- gls(SizeChange ~ MatingSystem+BSD+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test25<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test26<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test27<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test28<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test29<- gls(SizeChange ~ MatingSystem+NDVI+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test30<- gls(SizeChange ~ MatingSystem+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test31<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test32<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test33<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test34<- gls(SizeChange ~ BSD+NDVI+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test35<- gls(SizeChange ~ BSD+NDVI+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test36<- gls(SizeChange ~ BSD+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test37<- gls(SizeChange ~ NDVI+Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test38<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test39<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test40<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test41<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test42<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test43<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test44<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test45<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test46<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test47<- gls(SizeChange ~ MatingSystem+BSD+NDVI+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test48<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test49<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test50<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test51<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test52<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test53<- gls(SizeChange ~ MatingSystem+BSD+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test54<- gls(SizeChange ~ MatingSystem+BSD+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test55<- gls(SizeChange ~ MatingSystem+BSD+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test56<- gls(SizeChange ~ MatingSystem+BSD+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test57<- gls(SizeChange ~ MatingSystem+BSD+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test58<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test59<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test60<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test61<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test62<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test63<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test64<- gls(SizeChange ~ MatingSystem+NDVI+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test65<- gls(SizeChange ~ MatingSystem+NDVI+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test66<- gls(SizeChange ~ MatingSystem+NDVI+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test67<- gls(SizeChange ~ MatingSystem+NDVI+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test68<- gls(SizeChange ~ MatingSystem+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test69<- gls(SizeChange ~ MatingSystem+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test70<- gls(SizeChange ~ MatingSystem+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test71<- gls(SizeChange ~ MatingSystem+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test72<- gls(SizeChange ~ MatingSystem+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test73<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test74<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test75<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test76<- gls(SizeChange ~ BSD+NDVI+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test77<- gls(SizeChange ~ BSD+NDVI+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test78<- gls(SizeChange ~ BSD+NDVI+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test79<- gls(SizeChange ~ BSD+NDVI+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test80<- gls(SizeChange ~ BSD+NDVI+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test81<- gls(SizeChange ~ BSD+NDVI+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test82<- gls(SizeChange ~ BSD+NDVI+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test83<- gls(SizeChange ~ BSD+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test84<- gls(SizeChange ~ BSD+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test85<- gls(SizeChange ~ BSD+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test86<- gls(SizeChange ~ BSD+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test87<- gls(SizeChange ~ BSD+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test88<- gls(SizeChange ~ NDVI+Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test89<- gls(SizeChange ~ NDVI+Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test90<- gls(SizeChange ~ NDVI+Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test91<- gls(SizeChange ~ NDVI+Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test92<- gls(SizeChange ~ NDVI+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test93<- gls(SizeChange ~ Altitude+Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test94<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test95<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test96<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test97<- gls(SizeChange ~ MatingSystem+BSD+NDVI+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test98<- gls(SizeChange ~ MatingSystem+BSD+NDVI+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test99<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test100<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test101<- gls(SizeChange ~ MatingSystem+BSD+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test102<- gls(SizeChange ~ MatingSystem+BSD+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test103<- gls(SizeChange ~ MatingSystem+BSD+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test104<- gls(SizeChange ~ MatingSystem+BSD+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test105<- gls(SizeChange ~ MatingSystem+BSD+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test106<- gls(SizeChange ~ MatingSystem+BSD+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test107<- gls(SizeChange ~ MatingSystem+BSD+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test108<- gls(SizeChange ~ MatingSystem+BSD+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test109<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test110<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test111<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test112<- gls(SizeChange ~ MatingSystem+NDVI+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test113<- gls(SizeChange ~ MatingSystem+NDVI+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test114<- gls(SizeChange ~ MatingSystem+NDVI+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test115<- gls(SizeChange ~ MatingSystem+NDVI+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test116<- gls(SizeChange ~ MatingSystem+NDVI+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test117<- gls(SizeChange ~ MatingSystem+NDVI+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test118<- gls(SizeChange ~ MatingSystem+NDVI+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test119<- gls(SizeChange ~ MatingSystem+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test120<- gls(SizeChange ~ MatingSystem+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test121<- gls(SizeChange ~ MatingSystem+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test122<- gls(SizeChange ~ MatingSystem+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test123<- gls(SizeChange ~ MatingSystem+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test124<- gls(SizeChange ~ MatingSystem+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test125<- gls(SizeChange ~ MatingSystem+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test126<- gls(SizeChange ~ MatingSystem+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test127<- gls(SizeChange ~ MatingSystem+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test128<- gls(SizeChange ~ MatingSystem+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test129<- gls(SizeChange ~ BSD+NDVI+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test130<- gls(SizeChange ~ BSD+NDVI+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test131<- gls(SizeChange ~ BSD+NDVI+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test132<- gls(SizeChange ~ BSD+NDVI+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test133<- gls(SizeChange ~ BSD+NDVI+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test134<- gls(SizeChange ~ BSD+NDVI+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test135<- gls(SizeChange ~ BSD+NDVI+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test136<- gls(SizeChange ~ BSD+NDVI+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test137<- gls(SizeChange ~ BSD+NDVI+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test138<- gls(SizeChange ~ BSD+NDVI+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test139<- gls(SizeChange ~ BSD+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test140<- gls(SizeChange ~ BSD+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test141<- gls(SizeChange ~ BSD+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test142<- gls(SizeChange ~ BSD+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test143<- gls(SizeChange ~ BSD+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test144<- gls(SizeChange ~ BSD+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test145<- gls(SizeChange ~ BSD+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test146<- gls(SizeChange ~ BSD+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test147<- gls(SizeChange ~ BSD+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test148<- gls(SizeChange ~ BSD+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test149<- gls(SizeChange ~ NDVI+Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test150<- gls(SizeChange ~ NDVI+Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test151<- gls(SizeChange ~ NDVI+Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test152<- gls(SizeChange ~ NDVI+Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test153<- gls(SizeChange ~ NDVI+Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test154<- gls(SizeChange ~ NDVI+Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test155<- gls(SizeChange ~ NDVI+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test156<- gls(SizeChange ~ NDVI+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test157<- gls(SizeChange ~ NDVI+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test158<- gls(SizeChange ~ NDVI+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test159<- gls(SizeChange ~ Altitude+Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test160<- gls(SizeChange ~ Altitude+Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test161<- gls(SizeChange ~ Altitude+Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test162<- gls(SizeChange ~ Altitude+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test163<- gls(SizeChange ~ Temp+Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test164<- gls(SizeChange ~ MatingSystem+BSD+NDVI,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test165<- gls(SizeChange ~ MatingSystem+BSD+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test166<- gls(SizeChange ~ MatingSystem+BSD+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test167<- gls(SizeChange ~ MatingSystem+BSD+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test168<- gls(SizeChange ~ MatingSystem+BSD+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test169<- gls(SizeChange ~ MatingSystem+BSD+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test170<- gls(SizeChange ~ MatingSystem+NDVI+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test171<- gls(SizeChange ~ MatingSystem+NDVI+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test172<- gls(SizeChange ~ MatingSystem+NDVI+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test173<- gls(SizeChange ~ MatingSystem+NDVI+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test174<- gls(SizeChange ~ MatingSystem+NDVI+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test175<- gls(SizeChange ~ MatingSystem+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test176<- gls(SizeChange ~ MatingSystem+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test177<- gls(SizeChange ~ MatingSystem+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test178<- gls(SizeChange ~ MatingSystem+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test179<- gls(SizeChange ~ MatingSystem+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test180<- gls(SizeChange ~ MatingSystem+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test181<- gls(SizeChange ~ MatingSystem+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test182<- gls(SizeChange ~ MatingSystem+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test183<- gls(SizeChange ~ MatingSystem+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test184<- gls(SizeChange ~ MatingSystem+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test185<- gls(SizeChange ~ BSD+NDVI+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test186<- gls(SizeChange ~ BSD+NDVI+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test187<- gls(SizeChange ~ BSD+NDVI+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test188<- gls(SizeChange ~ BSD+NDVI+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test189<- gls(SizeChange ~ BSD+NDVI+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test190<- gls(SizeChange ~ BSD+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test191<- gls(SizeChange ~ BSD+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test192<- gls(SizeChange ~ BSD+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test193<- gls(SizeChange ~ BSD+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test194<- gls(SizeChange ~ BSD+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test195<- gls(SizeChange ~ BSD+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test196<- gls(SizeChange ~ BSD+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test197<- gls(SizeChange ~ BSD+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test198<- gls(SizeChange ~ BSD+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test199<- gls(SizeChange ~ BSD+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test200<- gls(SizeChange ~ NDVI+Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test201<- gls(SizeChange ~ NDVI+Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test202<- gls(SizeChange ~ NDVI+Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test203<- gls(SizeChange ~ NDVI+Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test204<- gls(SizeChange ~ NDVI+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test205<- gls(SizeChange ~ NDVI+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test206<- gls(SizeChange ~ NDVI+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test207<- gls(SizeChange ~ NDVI+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test208<- gls(SizeChange ~ NDVI+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test209<- gls(SizeChange ~ NDVI+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test210<- gls(SizeChange ~ Altitude+Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test211<- gls(SizeChange ~ Altitude+Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test212<- gls(SizeChange ~ Altitude+Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test213<- gls(SizeChange ~ Altitude+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test214<- gls(SizeChange ~ Altitude+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test215<- gls(SizeChange ~ Altitude+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test216<- gls(SizeChange ~ Temp+Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test217<- gls(SizeChange ~ Temp+Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test218<- gls(SizeChange ~ Temp+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test219<- gls(SizeChange ~ Solar+ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test220<- gls(SizeChange ~ MatingSystem+BSD,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test221<- gls(SizeChange ~ MatingSystem+NDVI,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test222<- gls(SizeChange ~ MatingSystem+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test223<- gls(SizeChange ~ MatingSystem+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test224<- gls(SizeChange ~ MatingSystem+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test225<- gls(SizeChange ~ MatingSystem+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test226<- gls(SizeChange ~ MatingSystem+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test227<- gls(SizeChange ~ BSD+NDVI,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test228<- gls(SizeChange ~ BSD+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test229<- gls(SizeChange ~ BSD+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test230<- gls(SizeChange ~ BSD+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test231<- gls(SizeChange ~ BSD+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test232<- gls(SizeChange ~ BSD+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test233<- gls(SizeChange ~ NDVI+Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test234<- gls(SizeChange ~ NDVI+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test235<- gls(SizeChange ~ NDVI+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test236<- gls(SizeChange ~ NDVI+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test237<- gls(SizeChange ~ NDVI+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test238<- gls(SizeChange ~ Altitude+Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test239<- gls(SizeChange ~ Altitude+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test240<- gls(SizeChange ~ Altitude+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test241<- gls(SizeChange ~ Altitude+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test242<- gls(SizeChange ~ Temp+Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test243<- gls(SizeChange ~ Temp+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test244<- gls(SizeChange ~ Temp+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test245<- gls(SizeChange ~ Solar+ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test246<- gls(SizeChange ~ Solar+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test247<- gls(SizeChange ~ ParentalCare+Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test248<- gls(SizeChange ~ MatingSystem,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test249<- gls(SizeChange ~ BSD,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test250<- gls(SizeChange ~ NDVI,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test251<- gls(SizeChange ~ Altitude,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test252<- gls(SizeChange ~ Temp,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test253<- gls(SizeChange ~ Solar,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test254<- gls(SizeChange ~ ParentalCare,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")
test255<- gls(SizeChange ~ Plumage_dim_sum,correlation=corMartins(1, phy=phas2_tree), data=phas2_BP,method="ML")

scores1<- summary(test1)
scores2<- summary(test2)
scores3<- summary(test3)
scores4<- summary(test4)
scores5<- summary(test5)
scores6<- summary(test6)
scores7<- summary(test7)
scores8<- summary(test8)
scores9<- summary(test9)
scores10<- summary(test10)
scores11<- summary(test11)
scores12<- summary(test12)
scores13<- summary(test13)
scores14<- summary(test14)
scores15<- summary(test15)
scores16<- summary(test16)
scores17<- summary(test17)
scores18<- summary(test18)
scores19<- summary(test19)
scores20<- summary(test20)
scores21<- summary(test21)
scores22<- summary(test22)
scores23<- summary(test23)
scores24<- summary(test24)
scores25<- summary(test25)
scores26<- summary(test26)
scores27<- summary(test27)
scores28<- summary(test28)
scores29<- summary(test29)
scores30<- summary(test30)
scores31<- summary(test31)
scores32<- summary(test32)
scores33<- summary(test33)
scores34<- summary(test34)
scores35<- summary(test35)
scores36<- summary(test36)
scores37<- summary(test37)
scores38<- summary(test38)
scores39<- summary(test39)
scores40<- summary(test40)
scores41<- summary(test41)
scores42<- summary(test42)
scores43<- summary(test43)
scores44<- summary(test44)
scores45<- summary(test45)
scores46<- summary(test46)
scores47<- summary(test47)
scores48<- summary(test48)
scores49<- summary(test49)
scores50<- summary(test50)
scores51<- summary(test51)
scores52<- summary(test52)
scores53<- summary(test53)
scores54<- summary(test54)
scores55<- summary(test55)
scores56<- summary(test56)
scores57<- summary(test57)
scores58<- summary(test58)
scores59<- summary(test59)
scores60<- summary(test60)
scores61<- summary(test61)
scores62<- summary(test62)
scores63<- summary(test63)
scores64<- summary(test64)
scores65<- summary(test65)
scores66<- summary(test66)
scores67<- summary(test67)
scores68<- summary(test68)
scores69<- summary(test69)
scores70<- summary(test70)
scores71<- summary(test71)
scores72<- summary(test72)
scores73<- summary(test73)
scores74<- summary(test74)
scores75<- summary(test75)
scores76<- summary(test76)
scores77<- summary(test77)
scores78<- summary(test78)
scores79<- summary(test79)
scores80<- summary(test80)
scores81<- summary(test81)
scores82<- summary(test82)
scores83<- summary(test83)
scores84<- summary(test84)
scores85<- summary(test85)
scores86<- summary(test86)
scores87<- summary(test87)
scores88<- summary(test88)
scores89<- summary(test89)
scores90<- summary(test90)
scores91<- summary(test91)
scores92<- summary(test92)
scores93<- summary(test93)
scores94<- summary(test94)
scores95<- summary(test95)
scores96<- summary(test96)
scores97<- summary(test97)
scores98<- summary(test98)
scores99<- summary(test99)
scores100<- summary(test100)
scores101<- summary(test101)
scores102<- summary(test102)
scores103<- summary(test103)
scores104<- summary(test104)
scores105<- summary(test105)
scores106<- summary(test106)
scores107<- summary(test107)
scores108<- summary(test108)
scores109<- summary(test109)
scores110<- summary(test110)
scores111<- summary(test111)
scores112<- summary(test112)
scores113<- summary(test113)
scores114<- summary(test114)
scores115<- summary(test115)
scores116<- summary(test116)
scores117<- summary(test117)
scores118<- summary(test118)
scores119<- summary(test119)
scores120<- summary(test120)
scores121<- summary(test121)
scores122<- summary(test122)
scores123<- summary(test123)
scores124<- summary(test124)
scores125<- summary(test125)
scores126<- summary(test126)
scores127<- summary(test127)
scores128<- summary(test128)
scores129<- summary(test129)
scores130<- summary(test130)
scores131<- summary(test131)
scores132<- summary(test132)
scores133<- summary(test133)
scores134<- summary(test134)
scores135<- summary(test135)
scores136<- summary(test136)
scores137<- summary(test137)
scores138<- summary(test138)
scores139<- summary(test139)
scores140<- summary(test140)
scores141<- summary(test141)
scores142<- summary(test142)
scores143<- summary(test143)
scores144<- summary(test144)
scores145<- summary(test145)
scores146<- summary(test146)
scores147<- summary(test147)
scores148<- summary(test148)
scores149<- summary(test149)
scores150<- summary(test150)
scores151<- summary(test151)
scores152<- summary(test152)
scores153<- summary(test153)
scores154<- summary(test154)
scores155<- summary(test155)
scores156<- summary(test156)
scores157<- summary(test157)
scores158<- summary(test158)
scores159<- summary(test159)
scores160<- summary(test160)
scores161<- summary(test161)
scores162<- summary(test162)
scores163<- summary(test163)
scores164<- summary(test164)
scores165<- summary(test165)
scores166<- summary(test166)
scores167<- summary(test167)
scores168<- summary(test168)
scores169<- summary(test169)
scores170<- summary(test170)
scores171<- summary(test171)
scores172<- summary(test172)
scores173<- summary(test173)
scores174<- summary(test174)
scores175<- summary(test175)
scores176<- summary(test176)
scores177<- summary(test177)
scores178<- summary(test178)
scores179<- summary(test179)
scores180<- summary(test180)
scores181<- summary(test181)
scores182<- summary(test182)
scores183<- summary(test183)
scores184<- summary(test184)
scores185<- summary(test185)
scores186<- summary(test186)
scores187<- summary(test187)
scores188<- summary(test188)
scores189<- summary(test189)
scores190<- summary(test190)
scores191<- summary(test191)
scores192<- summary(test192)
scores193<- summary(test193)
scores194<- summary(test194)
scores195<- summary(test195)
scores196<- summary(test196)
scores197<- summary(test197)
scores198<- summary(test198)
scores199<- summary(test199)
scores200<- summary(test200)
scores201<- summary(test201)
scores202<- summary(test202)
scores203<- summary(test203)
scores204<- summary(test204)
scores205<- summary(test205)
scores206<- summary(test206)
scores207<- summary(test207)
scores208<- summary(test208)
scores209<- summary(test209)
scores210<- summary(test210)
scores211<- summary(test211)
scores212<- summary(test212)
scores213<- summary(test213)
scores214<- summary(test214)
scores215<- summary(test215)
scores216<- summary(test216)
scores217<- summary(test217)
scores218<- summary(test218)
scores219<- summary(test219)
scores220<- summary(test220)
scores221<- summary(test221)
scores222<- summary(test222)
scores223<- summary(test223)
scores224<- summary(test224)
scores225<- summary(test225)
scores226<- summary(test226)
scores227<- summary(test227)
scores228<- summary(test228)
scores229<- summary(test229)
scores230<- summary(test230)
scores231<- summary(test231)
scores232<- summary(test232)
scores233<- summary(test233)
scores234<- summary(test234)
scores235<- summary(test235)
scores236<- summary(test236)
scores237<- summary(test237)
scores238<- summary(test238)
scores239<- summary(test239)
scores240<- summary(test240)
scores241<- summary(test241)
scores242<- summary(test242)
scores243<- summary(test243)
scores244<- summary(test244)
scores245<- summary(test245)
scores246<- summary(test246)
scores247<- summary(test247)
scores248<- summary(test248)
scores249<- summary(test249)
scores250<- summary(test250)
scores251<- summary(test251)
scores252<- summary(test252)
scores253<- summary(test253)
scores254<- summary(test254)
scores255<- summary(test255)

sink("SizeChange_Phasianidae_noSageGrouse_PGLS.txt")
print(scores1)
print(scores2)
print(scores3)
print(scores4)
print(scores5)
print(scores6)
print(scores7)
print(scores8)
print(scores9)
print(scores10)
print(scores11)
print(scores12)
print(scores13)
print(scores14)
print(scores15)
print(scores16)
print(scores17)
print(scores18)
print(scores19)
print(scores20)
print(scores21)
print(scores22)
print(scores23)
print(scores24)
print(scores25)
print(scores26)
print(scores27)
print(scores28)
print(scores29)
print(scores30)
print(scores31)
print(scores32)
print(scores33)
print(scores34)
print(scores35)
print(scores36)
print(scores37)
print(scores38)
print(scores39)
print(scores40)
print(scores41)
print(scores42)
print(scores43)
print(scores44)
print(scores45)
print(scores46)
print(scores47)
print(scores48)
print(scores49)
print(scores50)
print(scores51)
print(scores52)
print(scores53)
print(scores54)
print(scores55)
print(scores56)
print(scores57)
print(scores58)
print(scores59)
print(scores60)
print(scores61)
print(scores62)
print(scores63)
print(scores64)
print(scores65)
print(scores66)
print(scores67)
print(scores68)
print(scores69)
print(scores70)
print(scores71)
print(scores72)
print(scores73)
print(scores74)
print(scores75)
print(scores76)
print(scores77)
print(scores78)
print(scores79)
print(scores80)
print(scores81)
print(scores82)
print(scores83)
print(scores84)
print(scores85)
print(scores86)
print(scores87)
print(scores88)
print(scores89)
print(scores90)
print(scores91)
print(scores92)
print(scores93)
print(scores94)
print(scores95)
print(scores96)
print(scores97)
print(scores98)
print(scores99)
print(scores100)
print(scores101)
print(scores102)
print(scores103)
print(scores104)
print(scores105)
print(scores106)
print(scores107)
print(scores108)
print(scores109)
print(scores110)
print(scores111)
print(scores112)
print(scores113)
print(scores114)
print(scores115)
print(scores116)
print(scores117)
print(scores118)
print(scores119)
print(scores120)
print(scores121)
print(scores122)
print(scores123)
print(scores124)
print(scores125)
print(scores126)
print(scores127)
print(scores128)
print(scores129)
print(scores130)
print(scores131)
print(scores132)
print(scores133)
print(scores134)
print(scores135)
print(scores136)
print(scores137)
print(scores138)
print(scores139)
print(scores140)
print(scores141)
print(scores142)
print(scores143)
print(scores144)
print(scores145)
print(scores146)
print(scores147)
print(scores148)
print(scores149)
print(scores150)
print(scores151)
print(scores152)
print(scores153)
print(scores154)
print(scores155)
print(scores156)
print(scores157)
print(scores158)
print(scores159)
print(scores160)
print(scores161)
print(scores162)
print(scores163)
print(scores164)
print(scores165)
print(scores166)
print(scores167)
print(scores168)
print(scores169)
print(scores170)
print(scores171)
print(scores172)
print(scores173)
print(scores174)
print(scores175)
print(scores176)
print(scores177)
print(scores178)
print(scores179)
print(scores180)
print(scores181)
print(scores182)
print(scores183)
print(scores184)
print(scores185)
print(scores186)
print(scores187)
print(scores188)
print(scores189)
print(scores190)
print(scores191)
print(scores192)
print(scores193)
print(scores194)
print(scores195)
print(scores196)
print(scores197)
print(scores198)
print(scores199)
print(scores200)
print(scores201)
print(scores202)
print(scores203)
print(scores204)
print(scores205)
print(scores206)
print(scores207)
print(scores208)
print(scores209)
print(scores210)
print(scores211)
print(scores212)
print(scores213)
print(scores214)
print(scores215)
print(scores216)
print(scores217)
print(scores218)
print(scores219)
print(scores220)
print(scores221)
print(scores222)
print(scores223)
print(scores224)
print(scores225)
print(scores226)
print(scores227)
print(scores228)
print(scores229)
print(scores230)
print(scores231)
print(scores232)
print(scores233)
print(scores234)
print(scores235)
print(scores236)
print(scores237)
print(scores238)
print(scores239)
print(scores240)
print(scores241)
print(scores242)
print(scores243)
print(scores244)
print(scores245)
print(scores246)
print(scores247)
print(scores248)
print(scores249)
print(scores250)
print(scores251)
print(scores252)
print(scores253)
print(scores254)
print(scores255)
sink()
